version: 2
updates:
  - package-ecosystem: "helm"
    # The directory containing your Chart.yaml. 
    # Since yours is in the root, use "/"
    directory: "/" 
    schedule:
      interval: "daily"
      # Options: "daily", "weekly", "monthly"
      
    # Optional: Limit the number of open PRs to avoid noise
    open-pull-requests-limit: 10
    
    # Optional: Add labels to the PRs
    labels:
      - "dependencies"
      - "helm"
